akka {

  loglevel = INFO
  stdout-loglevel = INFO
  loggers = ["akka.event.slf4j.Slf4jLogger"]

  actor {

    provider = local

    default-dispatcher {
      type = Dispatcher
      executor = "fork-join-executor"

      fork-join-executor {
        parallelism-min = 2
        parallelism-factor = 1.0
        parallelism-max = 8
      }

      throughput = 100
    }

    scheduler {
      tick-duration = 10ms
      ticks-per-wheel = 512
    }
  }

  coordinated-shutdown {
    exit-jvm = off
  }

  http {

    server {
      preview.enable-http2 = off
      idle-timeout = 60s
      request-timeout = 30s
      max-connections = 1024
    }

    client {
      connecting-timeout = 10s
      idle-timeout = 60s
    }

    parsing {
      max-uri-length = 2048
      max-header-name-length = 64
      max-header-value-length = 8192
      max-header-count = 64
      max-content-length = 8m
    }

    host-connection-pool {

      min-connections = 0
      max-connections = 4

      max-open-requests = 32
      max-queue-size = 32

      pipelining-limit = 1
      max-retries = 5

      idle-timeout = 30s
      keep-alive-timeout = 30s
      connection-timeout = 10s

      response-entity-subscription-timeout = 10s

      per-host-override = []
    }
  }
}
